### ISSUE TITLE
Changing of the Guard

### ISSUE THREAD

**Issue by bburns632** [uptake/updoc#7]
Hey @kszela24, 

As requested, @Haoen-Cui will be taking over maintainer duties of this repo at the end of the week.  Please respond here or contact me directly if there are any issues. 

Hope all is well, 

@bburns632

**Comment by bburns632** [comment]
Thank you for creating such a valuable and stable package!

**Comment by kszela24** [comment]
Sounds great!

**Comment by Haoen-Cui** [comment]
Thanks @kszela24 for making this great package! It has been very helpful internally at Uptake and could be handy for other organizations as well. I'm excited to take over the maintainer tasks. I hope you will keep contributing in the future.

**Comment by bburns632** [comment]
This transition is complete.
